module.exports = {
    STATUS_CODE: {
      OK: 200,
      CREATED: 201,
      NO_CONTENT: 204,
      INFO: 250,
      BAD_REQUEST: 400,
      UN_AUTHORIZED: 401,
      FORBIDDEN: 403,
      RESOURCE_NOT_FOUND: 404,
      TOO_MANY_REQUESTS: 429,
      VALIDATION_FAILURE: 450,
      INTERNAL_SERVER_ERROR: 500,
      SERVICE_UNAVAILABLE: 503,
      SERVER_TIMEOUT: 504,
    },
    ERROR_MSGS: {
      AUTH_FAIL: 'Authentication failed.',
      INTERNAL_SERVER_ERROR: 'Unable to process,Please Try Again',
      INVALID_ROUTE: 'Requested API route is not available.',
      INVALID_CAPTCHA: 'Invalid captcha',
      CAPTCHA_IS_REQUIRED: 'Captcha is required',
      ORG_NOT_FOUND: 'Organization not found',
      ORG_BLOCKED: `Organization is blocked. Please contact admin`,
      ORG_DISABLED: `Your organization is disabled. Please contact admin`,
      INVALID_CREDENTIALS: `Invalid email or password.`,
      CLIENT_NOT_VERIFIED: 'Client not verified.',
      USER_ACCOUNT_DISABLED: `Your account has been disabled`,
      USER_ACCOUNT_BLOCKED: `Your account has been blocked`,
      USER_INVALID_ACCESS: `You don't have enough privileges to access`,
      USER_PORTAL_ACCESS_DISABLED: 'Portal access has been disabled',
      INVALID_ROLE: `Invalid Role`,
      USER_NOT_FOUND: `User not found`,
      EMAIL_NOT_VERIFIED: 'Email not verified, Please verify it.',
      CLIENT_ALREADY_EXISTS:
        'Company Name already exists, please contact your organization',
      EMAIL_VERIFY_TOKEN_NOT_FOUND: `We couldn't verify your email, Please try again.`,
      EMAIL_ALREADY_VERIFIED: `Your account has been already verified, Please login.`,
      ORGANIZATION_TOKEN_NOT_FOUND: 'Please provide valid organization details.',
      COMPANY_DOES_NOT_EXISTS: 'Company name does not exists.',
      CLIENT_NOT_FOUND: 'Client not found.',
      JWT_NOT_PROVIDED: 'No token provided',
      JWT_FORMAT_INVALID: 'Token invalid format',
      JWT_EXPIRED: `Token session expired`,
      JWT_INVALID_TOKEN_TYPE: 'Invalid Token type',
      OLD_PASSWORD:
        'Sorry! You Entered an Old Password. Please try a new password',
      INVALID_RESET_TOKEN: 'Invalid reset token.',
      RESEND_VERIFICATION_EMAIL_SUB_USER:
        'Please contact organization super user.',
      INCORRECT_PASSWORD: 'Incorrect current password.',
      TWO_FACTOR_ENABLED: '2FA already enabled',
      TWO_FACTOR_DISABLED: '2FA already disabled',
      TWO_FACTOR_NOT_ENABLED: '2FA is not enabled for this account',
      TWO_FACTOR_NOT_CONFIGURED: '2FA is not configured',
      TWO_FACTOR_SETUP_COMPLETED: '2FA setup already completed.',
      TWO_FACTOR_ENABLING_REQUIRED: 'Please enable 2FA to proceed further.',
      INVALID_CODE: 'Invalid code',
      ENTITY_REQUIRED: 'Entity type is a required ',
      ENTITY_INCORRECT: 'Please check entity type',
      FILES_REQUIRED: 'Please upload all required files and try again',
      UPLOAD_FAILED: 'Upload failed, Please try again',
      NO_KYC: 'KYC not yet submitted',
      KYB_ALREADY_VERIFIED: `KYB has been verified already`,
      KYC_ALREADY_VERIFIED: `KYC has been verified already`,
      KYC_FIRST: `Please complete KYC first and proceed with KYB`,
      EXTRACT_FILE_REQUIRED:
        'Please upload extract file to complete kyb submission.',
      INVALID_FILE_FORMAT:
        'Invalid file format. Supported files formats are jpg, jpeg, png, pdf',
      FILE_UPLOAD_FAILED: 'File upload failed, Please try again',
      STRIPE_ID_NOT_CREATED: 'Client not upgraded for payment.',
      NO_CARDS_ADDED: 'Card not added yet.',
      CARD_NOT_FOUND: 'Card not found.',
      CARD_ALREADY_EXISTS: 'Card already exists.',
      PLAN_NOT_FOUND: 'Service plan not found.',
      PLAN_DELETED: 'Service plan is currently unavailable.',
      PLAN_DISABLED: 'Service plan is currently unavailable.',
      PLAN_NOT_AVAILABLE: 'Service plan is unavailable for the portal.',
      PLAN_ALREADY_SUBSCRIBED: 'Already subscribed.',
      SUBSCRIPTION_NOT_FOUND: 'Subscription not found.',
      SUBSCRIPTION_EXPIRED: 'Subscription has been expired',
      SUBSCRIPTION_DISABLED: 'Subscription is disabled.',
      SUBSCRIPTION_ALREADY_VERIFIED: `Subscription has been verified already`,
      SUBSCRIPTION_ALREADY_SUBMITTED: `Subscription has been submitted already`,
      SUBSCRIPTION_ALREADY_ACTIVATED: `Subscription has been activated already`,
      COMPLETE_KYC_KYB: `Please complete your KYC and KYB verification`,
      SUBSCRIPTION_APPROVAL_REQUIRED: 'Subscription need to be approved by admin',
      SUBSCRIPTION_NOT_ACTIVATED: 'Subscription is not in an active state.',
      BUY_CREDITS_TO_USE: 'Buy credit to create a request.',
      MODS_MAX_CALL_LIMIT: 'Maximum limit is 5000000, please try lesser values',
      PAYMENT_ALREADY_ADDED: 'Payment already added.',
      SANDBOX_KEYS_ALREADY_CREATED: 'Sandbox keys have been already created.',
      CANNOT_CREATE_LIVE_KEYS: 'Buy credits to create live keys.',
      SUBSCRIPTION_NOT_EXPIRED: 'Subscription not expired.',
      SUBSCRIPTION_RENEWAL_FAILED: 'Subscription renewal failed.',
      SUB_USER_EXISTS: 'User already exists',
      SUB_USER_NOT_FOUND: 'Sub user not found',
      SUB_USER_ALREADY_ENABLED: 'Sub user is already enabled',
      SUB_USER_ALREADY_DISABLED: 'Sub user is already disabled',
      SUPER_USER_CAN_PERFORM: 'Only super user can perform the operation',
      INVALID_ENTITY_TYPE: 'Please check the entity type',
      KYB_SUBMISSION_FAILED: 'Kyb submission failed.Please try again.',
      KYB_UPDATE_FAILED: 'Kyb update failed.Please try again.',
      INVALID_PORTAL_PLANS: `Plans are available only for kreanoId`,
      API_AVAILABLE_FOR_REDACT:
        'Page Credit calculation is only available for Kreano-Redact',
      PAGE_LIMIT_REACHED: 'Maximum page limit is 200.',
      INSUFFICIENT_CREDITS: 'Insufficient credits for given page count',
      NOT_VALID_PHONE_NUMBER: 'Please enter a valid phone number.',
      AMOUNT_MUST_BE_GREATER: `Amount must be greater than or equal to 10AUD`,
      NO_IP_DETAILS_FOUND: 'No details found',
      MAX_ALLOWED_IP: `You are allowed to whitelist upto ${process.env.MAX_ALLOWED_IP} IP`,
      MODE_IS_ALREADY_PUBLIC: 'Mode is already public',
      IP_NOT_ALLOWED: `IP not allowed`,
      I_VERIFY_REQUEST_NOT_FOUND: 'iVerify request not found.',
      MESSAGE_ALREADY_SENT_SUCCESSFULLY:
        'iVerify request message already delivered successfully.',
      NO_MESSAGE_RESENT_OPTION:
        'iVerify request message resend can triggered only on failed message.',
      REQUEST_NOT_FOUND: 'IVerify Request not found.',
      INVALID_INPUT: 'Invalid input fields.',
      VERIFICATION_REQUEST_NOT_FOUND: 'Verification request not found.',
      LOGO_FILE_REQUIRED: 'Please upload the required logo file.',
      FILE_REQUIRED: 'Please upload the required file and try again',
      INVALID_LOGO_SIZE: 'Logo size should be less than 2 MB',
      RECOMMENDED_LOGO_SIZE: 'Invalid Image Size: Maximum Recommended 150 X 50',
    },
    INFO_MSGS: {
      NO_DATA: 'No data found',
      CREATED_SUCCESSFULLY: 'Created successfully',
      UPDATED_SUCCESSFULLY: 'Successfully updated',
      SUCCESS: 'Request Success',
      SUCCESSFUL_LOGIN: 'Successfully logged in',
      SUCCESSFUL_LOGOUT: 'Successfully logged out.',
      VERIFICATION_MAIL_SEND: 'Verification Email send successfully.',
      EMAIL_VERIFICATION_SUCCESS: `Your account has been verified, Please login.`,
      SUCCESSFUL_REFRESH_TOKEN: 'Successfully refreshed token.',
      FORGOT_PASSWORD_RESET_MAIL:
        'Email sent successfully to the registered account.',
      PASSWORD_RESET_SUCCESS: 'Password changed successfully! Please login.',
      PASSWORD_CHANGE_SUCCESS: 'Password changed successfully.',
      PROFILE_UPDATE_SUCCESS: 'Profile Successfully updated.',
      SUB_USER_UPDATE_SUCCESS: 'Sub-user Successfully updated.',
      USER_INFO_NOT_FOUND: 'User info not found.',
      TWO_FACTOR_SUCCESS: 'Successfully configured 2FA',
      TWO_FACTOR_ENABLED: '2FA enabled successfully',
      TWO_FACTOR_DISABLED: '2FA disabled successfully',
      SUCCESSFUL_ENABLE: '2FA enabling requested successfully.',
      SUCCESSFUL_RESET: '2FA is successfully reset on your request.',
      CARD_ADD_SUCCESSFUL: 'Card has been added successfully',
      NO_CARDS: 'Cards not yet added',
      CARD_REMOVED: 'Card removed successfully.',
      SUBSCRIPTION_APPROVAL_REQUESTED:
        'Request for admin approval submitted successfully.',
      BUY_CREDIT_SUCCESS:
        'Payment successfully completed and credits added to subscription.',
      KEY_GENERATED: 'Keys generated successfully',
      SUBSCRIPTION_RENEWED: 'Successfully renewed successfully.',
      NO_REDACTION_FILES: 'No files redacted yet.',
      NO_BIOMETRIC_FILES: 'No biometric report files yet.',
      NO_VERIFICATION_FILES: 'No verification report files yet.',
      NO_I_VERIFY_FILES: 'No iVerify report files yet.',
      SUB_USER_ADDED_SUCCESSFULLY: `Successfully added sub user`,
      SUB_USER_ENABLED: 'Successfully enabled sub user',
      SUB_USER_DISABLED: 'Successfully disabled sub user',
      SUB_USER_REMOVED: 'Successfully deleted sub user',
      NO_SUB_USERS: 'No sub users found',
      KEYS_NOT_CREATED: 'Access keys not created yet.',
      NO_CALLS_USED: 'No history found.',
      NO_SERVICES_AVAILABLE: 'No services available',
      KYC_SUBMITTED: 'KYC submitted successfully.',
      KYC_UPDATED: 'KYC updated successfully.',
      KYB_SUBMITTED: 'KYB submitted successfully.',
      KYB_UPDATED: 'KYB updated successfully.',
      KYB_NOT_SUBMITTED: 'KYB not yet submitted',
      KYC_NOT_SUBMITTED: 'KYC not yet submitted',
      SUBSCRIBE_SUCCESS: 'Subscribed successfully.',
      NO_CATEGORIES: 'No categories available.',
      MESSAGE_SEND_SUCCESSFULLY: 'Message sent successfully.',
      I_VERIFY_REQUEST_SEND_SUCCESSFULLY:
        'Your request has been sent successfully.',
      EMPLOYEE_VERIFICATION_SUCCESS: 'Thanks for your response',
      REQUEST_ALREADY_UPDATED: 'Thanks for your time, response already given.',
      COMPANY_LOGO_ADDED: 'Company logo successfully uploaded.',
    },
  };
  